export const PRODUCTS = [
  {
    id: "1",
    name: "Blush Lace",
    slug: "blush-lace",
    description: "Intricately embossed lace texture sculpted in soft blush pink. Ultra-slim profile with anti-scratch coating and tactile button covers.",
    price: "99",
    comparePrice: null,
    images: ["/images/products/rose-gold.svg"],
    badge: "bestseller",
    isFeatured: true,
    categoryId: "cat-4",
    categoryName: "Designer",
    modelSlug: "iphone-15-pro-max",
    modelName: "iPhone 15 Pro Max",
    viewCount: 342,
    orderCount: 114,
    stock: 28,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 15 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 13 },
    ],
  },
  {
    id: "2",
    name: "Whatever I Am",
    slug: "whatever-i-am",
    description: "Signature typography edition on electric azure sky blue. Dual-composite protection with raised camera bezels.",
    price: "99",
    comparePrice: null,
    images: ["/images/products/royal-blue.svg"],
    badge: "new",
    isFeatured: true,
    categoryId: "cat-4",
    categoryName: "Designer",
    modelSlug: "iphone-15-pro",
    modelName: "iPhone 15 Pro",
    viewCount: 289,
    orderCount: 92,
    stock: 22,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 12 },
      { id: "m2", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 10 },
    ],
  },
  {
    id: "3",
    name: "Diamond Mesh Gold",
    slug: "diamond-mesh-gold",
    description: "Hand-set gold mesh fringe with crystalline diamond pave reflections. The ultimate Qatar evening accessory.",
    price: "149",
    comparePrice: "189",
    images: ["/images/products/gold-edge.svg"],
    badge: "bestseller",
    isFeatured: true,
    categoryId: "cat-2",
    categoryName: "Premium",
    modelSlug: "iphone-15-pro-max",
    modelName: "iPhone 15 Pro Max",
    viewCount: 512,
    orderCount: 168,
    stock: 14,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 8 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 6 },
    ],
  },
  {
    id: "4",
    name: "Midnight Black",
    slug: "midnight-black",
    description: "Machined from aerospace composite with matte velvet hand-feel. High-impact perimeter bumper and MagSafe alignment.",
    price: "79",
    comparePrice: "99",
    images: ["/images/products/midnight-black.svg"],
    badge: null,
    isFeatured: true,
    categoryId: "cat-2",
    categoryName: "Premium",
    modelSlug: "iphone-15-pro",
    modelName: "iPhone 15 Pro",
    viewCount: 234,
    orderCount: 89,
    stock: 24,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 8 },
      { id: "m2", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 10 },
      { id: "m3", name: "Samsung Galaxy S24 Ultra", slug: "samsung-galaxy-s24-ultra", brand: "Samsung", stock: 6 },
    ],
  },
  {
    id: "5",
    name: "Gold Edge Luxe",
    slug: "gold-edge-luxe",
    description: "A statement silhouette framed with electroplated gold accents. Hand-finished for Qatar flagship device owners.",
    price: "129",
    comparePrice: null,
    images: ["/images/products/gold-edge.svg"],
    badge: "new",
    isFeatured: true,
    categoryId: "cat-2",
    categoryName: "Premium",
    modelSlug: "iphone-15-pro-max",
    modelName: "iPhone 15 Pro Max",
    viewCount: 156,
    orderCount: 34,
    stock: 15,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 8 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 7 },
    ],
  },
  {
    id: "6",
    name: "Matte Carbon Fiber",
    slug: "matte-carbon-fiber",
    description: "Ultra-rigid woven carbon fiber weave. Featherlight, scratch-resistant armor for executive devices.",
    price: "89",
    comparePrice: null,
    images: ["/images/products/carbon-fiber.svg"],
    badge: null,
    isFeatured: true,
    categoryId: "cat-3",
    categoryName: "Sport",
    modelSlug: "google-pixel-8-pro",
    modelName: "Google Pixel 8 Pro",
    viewCount: 145,
    orderCount: 45,
    stock: 12,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "Google Pixel 8 Pro", slug: "google-pixel-8-pro", brand: "Google", stock: 6 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 6 },
    ],
  },
  {
    id: "7",
    name: "Crystal Clear",
    slug: "crystal-clear",
    description: "Show off your phone's original titanium design while keeping it pristine. 100% anti-yellowing optical composite.",
    price: "49",
    comparePrice: null,
    images: ["/images/products/clear-crystal.svg"],
    badge: null,
    isFeatured: false,
    categoryId: "cat-1",
    categoryName: "Classic",
    modelSlug: "iphone-15-pro",
    modelName: "iPhone 15 Pro",
    viewCount: 210,
    orderCount: 112,
    stock: 30,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 10 },
      { id: "m2", name: "iPhone 15", slug: "iphone-15", brand: "iPhone", stock: 10 },
      { id: "m3", name: "Samsung Galaxy S24", slug: "samsung-galaxy-s24", brand: "Samsung", stock: 10 },
    ],
  },
  {
    id: "8",
    name: "Forest Green Leather",
    slug: "forest-green-leather",
    description: "Full-grain supple calfskin leather in deep emerald green. Ages gracefully with an authentic Qatar patina.",
    price: "119",
    comparePrice: null,
    images: ["/images/products/forest-green.svg"],
    badge: "new",
    isFeatured: true,
    categoryId: "cat-2",
    categoryName: "Premium",
    modelSlug: "iphone-15-pro-max",
    modelName: "iPhone 15 Pro Max",
    viewCount: 98,
    orderCount: 23,
    stock: 6,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 3 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 3 },
    ],
  },
];

export const MODELS = [
  { id: "1", brand: "iPhone", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", count: 6 },
  { id: "2", brand: "iPhone", name: "iPhone 15 Pro", slug: "iphone-15-pro", count: 7 },
  { id: "3", brand: "iPhone", name: "iPhone 15", slug: "iphone-15", count: 3 },
  { id: "4", brand: "Samsung", name: "Samsung Galaxy S24 Ultra", slug: "samsung-galaxy-s24-ultra", count: 4 },
  { id: "5", brand: "Samsung", name: "Samsung Galaxy S24", slug: "samsung-galaxy-s24", count: 4 },
  { id: "6", brand: "Google", name: "Google Pixel 8 Pro", slug: "google-pixel-8-pro", count: 3 },
];

export const CATEGORIES = [
  { id: "cat-1", name: "Classic", slug: "classic", description: "Timeless elegance", count: 2 },
  { id: "cat-2", name: "Premium", slug: "premium", description: "Luxury materials", count: 3 },
  { id: "cat-3", name: "Sport", slug: "sport", description: "Active lifestyle", count: 2 },
  { id: "cat-4", name: "Designer", slug: "designer", description: "Limited editions", count: 2 },
];

export const ORDERS = [
  { id: "ORD-248", customer: "Rashid Al-Kuwari", phone: "+974 5512 3456", items: [{ name: "Midnight Black", model: "iPhone 15 Pro", qty: 1, price: 79 }], total: 79, status: "pending", createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), address: "The Pearl - Porto Arabia, Tower 22, Doha" },
  { id: "ORD-247", customer: "Fatima Al-Thani", phone: "+974 5523 4567", items: [{ name: "Diamond Mesh Gold", model: "iPhone 15 Pro Max", qty: 1, price: 149 }], total: 149, status: "confirmed", createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(), address: "West Bay Lagoon, Villa 14, Doha" },
  { id: "ORD-246", customer: "Ahmed Al-Sulaiti", phone: "+974 5534 5678", items: [{ name: "Whatever I Am", model: "iPhone 15 Pro", qty: 1, price: 99 }], total: 99, status: "dispatched", createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), address: "Lusail Marina, Tower 5, Lusail" },
  { id: "ORD-245", customer: "Sara Al-Khelaifi", phone: "+974 5545 6789", items: [{ name: "Blush Lace", model: "iPhone 15 Pro Max", qty: 1, price: 99 }], total: 99, status: "delivered", createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), address: "Al Waab, Street 340, Doha" },
  { id: "ORD-244", customer: "Omar Al-Kuwari", phone: "+974 5556 7890", items: [{ name: "Matte Carbon Fiber", model: "Pixel 8 Pro", qty: 1, price: 89 }], total: 89, status: "confirmed", createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), address: "Al Khor Community, Villa 88, Al Khor" },
  { id: "ORD-243", customer: "Maryam Al-Mannai", phone: "+974 5567 8901", items: [{ name: "Forest Green Leather", model: "iPhone 15 Pro Max", qty: 1, price: 119 }], total: 119, status: "pending", createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), address: "Al Wakrah, Souq Area, Al Wakrah" },
];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByModel(modelSlug: string) {
  return PRODUCTS.filter((p) => p.modelSlug === modelSlug || p.models.some((m) => m.slug === modelSlug));
}

export function getProductsByCategory(categorySlug: string) {
  return PRODUCTS.filter((p) => p.categoryName.toLowerCase() === categorySlug);
}

export function getFeaturedProducts() {
  return PRODUCTS.filter((p) => p.isFeatured);
}

export function getOrdersByPhone(phone: string) {
  return ORDERS.filter((o) => o.phone === phone);
}
