export const PRODUCTS = [
  {
    id: "1",
    name: "Midnight Black Premium Case",
    slug: "midnight-black-premium-case",
    description: "Machined from aerospace composite with matte velvet hand-feel. High-impact perimeter bumper and MagSafe alignment.",
    price: "79",
    comparePrice: "99",
    images: ["/images/products/midnight-black.svg"],
    badge: "bestseller",
    isFeatured: true,
    categoryId: "cat-2",
    categoryName: "Premium",
    modelSlug: "iphone-15-pro",
    modelName: "iPhone 15 Pro",
    viewCount: 234,
    orderCount: 89,
    stock: 24,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 8 },
      { id: "m2", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 10 },
      { id: "m3", name: "Samsung Galaxy S24 Ultra", slug: "samsung-galaxy-s24-ultra", brand: "Samsung", stock: 6 },
    ],
  },
  {
    id: "2",
    name: "Gold Edge Luxe Case",
    slug: "gold-edge-luxe-case",
    description: "A statement silhouette framed with electroplated gold accents. Hand-finished for Qatar flagship device owners.",
    price: "129",
    comparePrice: null,
    images: ["/images/products/gold-edge.svg"],
    badge: "new",
    isFeatured: true,
    categoryId: "cat-2",
    categoryName: "Premium",
    modelSlug: "iphone-15-pro-max",
    modelName: "iPhone 15 Pro Max",
    viewCount: 156,
    orderCount: 34,
    stock: 15,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 8 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 7 },
    ],
  },
  {
    id: "3",
    name: "Royal Blue Classic Case",
    slug: "royal-blue-classic-case",
    description: "Classic design meets modern defense. Deep royal luster with micron-level camera bevel protection.",
    price: "59",
    comparePrice: "79",
    images: ["/images/products/royal-blue.svg"],
    badge: "sale",
    isFeatured: false,
    categoryId: "cat-1",
    categoryName: "Classic",
    modelSlug: "samsung-galaxy-s24-ultra",
    modelName: "Samsung Galaxy S24 Ultra",
    viewCount: 189,
    orderCount: 67,
    stock: 18,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "Samsung Galaxy S24 Ultra", slug: "samsung-galaxy-s24-ultra", brand: "Samsung", stock: 6 },
      { id: "m2", name: "Samsung Galaxy S24", slug: "samsung-galaxy-s24", brand: "Samsung", stock: 6 },
      { id: "m3", name: "iPhone 15", slug: "iphone-15", brand: "iPhone", stock: 6 },
    ],
  },
  {
    id: "4",
    name: "Matte Carbon Fiber Case",
    slug: "matte-carbon-fiber-case",
    description: "Ultra-rigid woven carbon fiber weave. Featherlight, scratch-resistant armor for executive devices.",
    price: "89",
    comparePrice: null,
    images: ["/images/products/carbon-fiber.svg"],
    badge: null,
    isFeatured: true,
    categoryId: "cat-3",
    categoryName: "Sport",
    modelSlug: "google-pixel-8-pro",
    modelName: "Google Pixel 8 Pro",
    viewCount: 145,
    orderCount: 45,
    stock: 12,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "Google Pixel 8 Pro", slug: "google-pixel-8-pro", brand: "Google", stock: 6 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 6 },
    ],
  },
  {
    id: "5",
    name: "Clear Crystal Case",
    slug: "clear-crystal-case",
    description: "Show off your phone's original titanium design while keeping it pristine. 100% anti-yellowing optical composite.",
    price: "49",
    comparePrice: null,
    images: ["/images/products/clear-crystal.svg"],
    badge: null,
    isFeatured: false,
    categoryId: "cat-1",
    categoryName: "Classic",
    modelSlug: "iphone-15-pro",
    modelName: "iPhone 15 Pro",
    viewCount: 210,
    orderCount: 112,
    stock: 30,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 10 },
      { id: "m2", name: "iPhone 15", slug: "iphone-15", brand: "iPhone", stock: 10 },
      { id: "m3", name: "Samsung Galaxy S24", slug: "samsung-galaxy-s24", brand: "Samsung", stock: 10 },
    ],
  },
  {
    id: "6",
    name: "Rose Gold Slim Case",
    slug: "rose-gold-slim-case",
    description: "Ultra-slim profile with a stunning metallic champagne rose sheen. Currently sold out in Qatar atelier.",
    price: "69",
    comparePrice: "89",
    images: ["/images/products/rose-gold.svg"],
    badge: "sale",
    isFeatured: false,
    categoryId: "cat-4",
    categoryName: "Designer",
    modelSlug: "samsung-galaxy-s24-ultra",
    modelName: "Samsung Galaxy S24 Ultra",
    viewCount: 167,
    orderCount: 52,
    stock: 0,
    inStock: false,
    lastSoldAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "Samsung Galaxy S24 Ultra", slug: "samsung-galaxy-s24-ultra", brand: "Samsung", stock: 0 },
      { id: "m2", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 0 },
    ],
  },
  {
    id: "7",
    name: "Forest Green Leather Case",
    slug: "forest-green-leather-case",
    description: "Full-grain supple calfskin leather in deep emerald green. Ages gracefully with an authentic Qatar patina.",
    price: "119",
    comparePrice: null,
    images: ["/images/products/forest-green.svg"],
    badge: "new",
    isFeatured: true,
    categoryId: "cat-2",
    categoryName: "Premium",
    modelSlug: "iphone-15-pro-max",
    modelName: "iPhone 15 Pro Max",
    viewCount: 98,
    orderCount: 23,
    stock: 6,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", brand: "iPhone", stock: 3 },
      { id: "m2", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 3 },
    ],
  },
  {
    id: "8",
    name: "Matte Black Armor Case",
    slug: "matte-black-armor-case",
    description: "Tactical defense geometry with 12ft drop certified corners. Dual-layer shock absorption system.",
    price: "99",
    comparePrice: null,
    images: ["/images/products/matte-black.svg"],
    badge: "bestseller",
    isFeatured: true,
    categoryId: "cat-3",
    categoryName: "Sport",
    modelSlug: "google-pixel-8-pro",
    modelName: "Google Pixel 8 Pro",
    viewCount: 178,
    orderCount: 61,
    stock: 20,
    inStock: true,
    lastSoldAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    models: [
      { id: "m1", name: "Google Pixel 8 Pro", slug: "google-pixel-8-pro", brand: "Google", stock: 7 },
      { id: "m2", name: "Samsung Galaxy S24 Ultra", slug: "samsung-galaxy-s24-ultra", brand: "Samsung", stock: 7 },
      { id: "m3", name: "iPhone 15 Pro", slug: "iphone-15-pro", brand: "iPhone", stock: 6 },
    ],
  },
];

export const MODELS = [
  { id: "1", brand: "iPhone", name: "iPhone 15 Pro Max", slug: "iphone-15-pro-max", count: 4 },
  { id: "2", brand: "iPhone", name: "iPhone 15 Pro", slug: "iphone-15-pro", count: 6 },
  { id: "3", brand: "iPhone", name: "iPhone 15", slug: "iphone-15", count: 2 },
  { id: "4", brand: "Samsung", name: "Samsung Galaxy S24 Ultra", slug: "samsung-galaxy-s24-ultra", count: 3 },
  { id: "5", brand: "Samsung", name: "Samsung Galaxy S24", slug: "samsung-galaxy-s24", count: 4 },
  { id: "6", brand: "Google", name: "Google Pixel 8 Pro", slug: "google-pixel-8-pro", count: 3 },
];

export const CATEGORIES = [
  { id: "cat-1", name: "Classic", slug: "classic", description: "Timeless elegance", count: 2 },
  { id: "cat-2", name: "Premium", slug: "premium", description: "Luxury materials", count: 3 },
  { id: "cat-3", name: "Sport", slug: "sport", description: "Active lifestyle", count: 2 },
  { id: "cat-4", name: "Designer", slug: "designer", description: "Limited editions", count: 1 },
];

export const ORDERS = [
  { id: "ORD-248", customer: "Rashid Al-Kuwari", phone: "+974 5512 3456", items: [{ name: "Midnight Black Case", model: "iPhone 15 Pro", qty: 1, price: 79 }], total: 79, status: "pending", createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), address: "The Pearl - Porto Arabia, Tower 22, Doha" },
  { id: "ORD-247", customer: "Fatima Al-Thani", phone: "+974 5523 4567", items: [{ name: "Gold Edge Luxe", model: "iPhone 15 Pro Max", qty: 1, price: 129 }], total: 129, status: "confirmed", createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(), address: "West Bay Lagoon, Villa 14, Doha" },
  { id: "ORD-246", customer: "Ahmed Al-Sulaiti", phone: "+974 5534 5678", items: [{ name: "Royal Blue Classic", model: "Samsung S24 Ultra", qty: 1, price: 59 }], total: 59, status: "dispatched", createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), address: "Lusail Marina, Tower 5, Lusail" },
  { id: "ORD-245", customer: "Sara Al-Khelaifi", phone: "+974 5545 6789", items: [{ name: "Clear Crystal", model: "iPhone 15 Pro", qty: 1, price: 49 }], total: 49, status: "delivered", createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), address: "Al Waab, Street 340, Doha" },
  { id: "ORD-244", customer: "Omar Al-Kuwari", phone: "+974 5556 7890", items: [{ name: "Matte Black Armor", model: "Pixel 8 Pro", qty: 1, price: 99 }], total: 99, status: "confirmed", createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), address: "Al Khor Community, Villa 88, Al Khor" },
  { id: "ORD-243", customer: "Maryam Al-Mannai", phone: "+974 5567 8901", items: [{ name: "Forest Green Leather", model: "iPhone 15 Pro Max", qty: 1, price: 119 }], total: 119, status: "pending", createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), address: "Al Wakrah, Souq Area, Al Wakrah" },
];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByModel(modelSlug: string) {
  return PRODUCTS.filter((p) => p.modelSlug === modelSlug || p.models.some((m) => m.slug === modelSlug));
}

export function getProductsByCategory(categorySlug: string) {
  return PRODUCTS.filter((p) => p.categoryName.toLowerCase() === categorySlug);
}

export function getFeaturedProducts() {
  return PRODUCTS.filter((p) => p.isFeatured);
}

export function getOrdersByPhone(phone: string) {
  return ORDERS.filter((o) => o.phone === phone);
}
